### ISSUE TITLE
Assigment 07 -- 27 Mar 2024

### ISSUE THREAD

**Issue by dudung** [dudung/sk6093-01-2023-2#7]
+ Update your presence status on [SIX](https://akademik.itb.ac.id/).
+ Create issue(s) your repository for encountered problem(s).
+ Put link to the issue(s) here.

**Comment by NitaDwiFitriani** [comment]
Nama : Nita Dwi Fitriani
Nim :  20922303

Link : https://github.com/NitaDwiFitriani/20922303_Nita-Dwi-Fitriani/commit/fa955f299591c383c4ca2f33c4af830ec773feba

I included the following issue in the Commit Report for Task 7:
1. Doping with Al, Cu, Mo, and W in TiO2 improves the DOS phonon graph because they affect the structure and interactions in the TiO2 crystal, causing an increase in phonon energy at some energy points. This indicates a significant change in the vibrational properties of TiO2 that is potentially important in technological applications.

2. Vacancy in the FeS material does not show a significant change in the graph, the vacancy result of 8% with perfect material still produces the same prediction, it needs to be reviewed

**Comment by abraar4100** [comment]
**Link to the issue:**
- https://github.com/abraar4100/sk6093/issues/1
- The main program shows error when processing the maximum sharpe ratio baseline. However, it does not affect the environment of the DQN Algorithm

**Comment by alitadinugraha** [comment]
**Issue:** getting google API keys and videoId, create application's API key guide.
**Link to the issue:** https://github.com/alitadinugraha/YT-comment-scraper/issues/1
