### ISSUE TITLE
Midterm -- 03 Apr 2024

### ISSUE THREAD

**Issue by dudung** [dudung/sk6093-01-2023-2#8]
- Make a table containing all elements or components that a repository should have.
- Elements are put in the first column.
- Second column is for progress, and inform progress for each elements.
- Third column is for date to accomplish each elements.

**Comment by abraar4100** [comment]
**Below is the following table:**

| Elements  | Progress | Date to accomplish | 
| ------------- | ------------- | ------------- |
| README.md  | Completed | March 1 |
| LICENSE | Completed | March 1 |
| Main Program | In progress | April 7 |
| DRL Environment | In progress | April 7 |

**Below is the detailed version of the progress of the main program and DRL Environment**

| Progress  | Date to accomplish | Progress | 
| ------------- | ------------- | ------------- |
| Building the DRL Environment Pt. 1  | March 26 |  Building the _reset_ function for each episode |
| Building the DRL Environment Pt. 2 | March 30 |  Building the _update_current_allocations_ function correlated to the actions in stock market: buy, sell, hold |
| Building the DRL Environment Pt. 3  | April 4 |  Building the _get_observation_ function correlated to each agent's observation |
| Building the DRL Environment Pt. 4  | April 4 |  Building the _step_ function to define the following step to be taken in stock market transaction|
| Building the DRL Environment Pt. 5 (end) | April 4 |  Building the _update_current_value_ function to update current portfolio value |
| Building the Main Program Pt. 1 | April 5 |  Building the main program notebook to run the environment |
| GitHub Repo Update Pt. 1 | April 5 |  Temporary GitHub repo update  |
| Building the Main Program Pt. 2 | April 6 |  Building the main program notebook to run the environment (analysis) |
| Building the Main Program Pt. 3 (end) | April 6 |  Building the main program notebook to run the environment (end) |
| Revision Pt. 1 | April 7 | Revision |
| Revision Pt. 2 | April 7 | Revision |

Thank you, Pak Dudung.

**Comment by NitaDwiFitriani** [comment]
Nama : Nita Dwi Fitriani
Nim :  20922303

The following advancements are in progress and have started to be finalized, but on the problem part, I am still looking for ways to get more accurate results at this point. 

| Elements         | Progress    | Date to Accomplish |
|------------------|-------------|--------------------|
| README.md        | Completed   | March 1            |
| LICENSE          | Completed   | March 24           |
| Data Preparation | Completed | April 3            |
| Main Program     | In progress | April 7            |
| Analysis of results    | In progress | Mei 8            |

| Stage              | Progress   | Date to Accomplish | Description                                                                                                                        | Problem                                                                                                                               |
|--------------------|------------|---------------------|------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|
| Planning Stage     | Completed  | March 6             | Planning the project and selecting the development                                                                               | Learn Material Science Especially Phonon DOS and Model E3NN                                                                     |
| Design Stage       | Completed  | March 13            | Designing software architecture                                                                                                    | Creating architecture in accordance with the methods used with literacy understanding from journals                               |
| Implementation Stage | Completed | April 17            | Beginning/Continuing implementation of features                                                                                   | Prepare for testing orthorhombic FeS new material with Multi-dimensional data                                                      |
| Sprint 1 Review    | Completed  | March 27            | Reviewing progress after Sprint 1                                                                                                  | Difficulty in preparing complex data with tools and ensuring data suitability through visualization and validation with VESTA, Existence of multidimensional data requiring preprocessing |
| Sprint 2 Planning  | Completed  | April 10            | Planning Sprint 2 based on feedback                                                                                                | Testing Supercell material with TiO2 doping Al, Cu, Mo, and W, observe the results, and try to vacancy data                     |
| Testing Stage      | In progress| May 1               | Initiating/further testing                                                                                                         | Doping with Al, Cu, Mo, and W in TiO2 improves the DOS phonon graph because they affect the structure and interactions in the TiO2 crystal, causing an increase in phonon energy at some energy points. This indicates a significant change in the vibrational properties of TiO2 that is potentially important in technological applications. Vacancy in the FeS material does not show a significant change in the graph, the vacancy result of 8% with perfect material still produces the same prediction, it needs to be reviewed |
| Sprint 2 Review    | Not started| April 24            | Reviewing progress after Sprint 2                                                                                                  | None                                                                                                                                 |
| Sprint 3 Planning  | Not started| May 8               | Planning Sprint 3 based on feedback                                                                                                | None                                                                                                                                 |
| Sprint 3 Review    | Not started| May 22              | Reviewing progress after Sprint 3                                                                                                  | None                                                                                                                                 |
| Finalization       | Not started| May 29              | Completing documentation and preparing final report                                                                                | None                                                                                                                                 |

**Comment by alitadinugraha** [comment]
**Remed-exam**: Independent Research in Computational Science 3 (SK6093)
Dewa Made Alit Adinugraha (20922006)

| Element | Progress | Date to Accomplish |
| ------------- | ------------- | ------------- |
| Readme | completed | March 20 |
| LICENSE | completed | March 20 |
| YTcommentscrap.ipynb | completed | April 10 |
| Main.ipnyb | completed | April 10 |

Timeline and stages:
| Progress  | Date of completion | Description |
| ------------- | ------------- | ------------- |
| System Requirements Analysis | March 4 | The system was carried out to determine the needs that will later be used in developing the system |
| System design | March 9 | System design aims to create a design from the results of the analysis that has been carried out in the previous stage |
| Getting API | March 10 | get API from Google to be used in the data retrieval process |
| System Build | March 10 - April 20 | Building the main program |
| 1st System Testing | March 20 | The first stage of the system test is carried out to see whether there are results in obtaining data from YouTube |
| 2nd System Testing | April 10 | The second stage of the system test is carried out to get the data pre-processing result before analysis |
| 3rd System Testing | April 20 | The third stage of the system test is carried out to get the result of data test and data train before analysis |
| Final System Testing | April 25 | test whether the system built is in accordance with the design and expected output |
| GitHub Repository Update | March 10 - Finish | update GitHub Repository |
| Documentation | April 30 | document the results of the analysis |
